// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: Setting_Wi-Fi_Password

#include "../ui.h"
#include "ui_scale.h"

void ui_ScreenSettingVerification_screen_init(void)
{
    ui_ScreenSettingVerification = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenSettingVerification, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenSettingVerification, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenSettingVerification, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScreenSettingVerification = lv_label_create(ui_ScreenSettingVerification);
    lv_obj_set_width(ui_LabelScreenSettingVerification, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScreenSettingVerification, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScreenSettingVerification, UI_SX(-335));
    lv_obj_set_y(ui_LabelScreenSettingVerification, UI_SY(-155));
    lv_obj_set_align(ui_LabelScreenSettingVerification, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelScreenSettingVerification, "SSID:");
    lv_obj_set_style_text_font(ui_LabelScreenSettingVerification, ui_font_scaled(30), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelScreenSettingVerificationSSID = lv_label_create(ui_ScreenSettingVerification);
    lv_obj_set_width(ui_LabelScreenSettingVerificationSSID, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelScreenSettingVerificationSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelScreenSettingVerificationSSID, UI_SX(-175));
    lv_obj_set_y(ui_LabelScreenSettingVerificationSSID, UI_SY(-155));
    lv_obj_set_align(ui_LabelScreenSettingVerificationSSID, LV_ALIGN_CENTER);
    lv_obj_set_style_text_font(ui_LabelScreenSettingVerificationSSID, ui_font_scaled(30),
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaScreenSettingVerificationPassword = lv_textarea_create(ui_ScreenSettingVerification);
    lv_obj_set_width(ui_TextAreaScreenSettingVerificationPassword, UI_SX(640));
    lv_obj_set_height(ui_TextAreaScreenSettingVerificationPassword, UI_SY(66));
    lv_obj_set_x(ui_TextAreaScreenSettingVerificationPassword, UI_SX(-9));
    lv_obj_set_y(ui_TextAreaScreenSettingVerificationPassword, UI_SY(-70));
    lv_obj_set_align(ui_TextAreaScreenSettingVerificationPassword, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaScreenSettingVerificationPassword, "Password...");
    lv_obj_set_style_text_font(ui_TextAreaScreenSettingVerificationPassword, ui_font_scaled(30),
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardScreenSettingVerification = lv_keyboard_create(ui_ScreenSettingVerification);
    lv_obj_set_width(ui_KeyboardScreenSettingVerification, UI_SX(800));
    lv_obj_set_height(ui_KeyboardScreenSettingVerification, UI_SY(210));
    lv_obj_set_x(ui_KeyboardScreenSettingVerification, UI_SX(-1));
    lv_obj_set_y(ui_KeyboardScreenSettingVerification, UI_SY(120));
    lv_obj_set_align(ui_KeyboardScreenSettingVerification, LV_ALIGN_CENTER);

    ui_SpinnerScreenSettingVerification = lv_spinner_create(ui_ScreenSettingVerification, 1000, 90);
    lv_obj_set_width(ui_SpinnerScreenSettingVerification, UI_SX(153));
    lv_obj_set_height(ui_SpinnerScreenSettingVerification, UI_SY(180));
    lv_obj_set_x(ui_SpinnerScreenSettingVerification, UI_SX(-24));
    lv_obj_set_y(ui_SpinnerScreenSettingVerification, UI_SY(-116));
    lv_obj_set_align(ui_SpinnerScreenSettingVerification, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpinnerScreenSettingVerification, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_SpinnerScreenSettingVerification, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_arc_width(ui_SpinnerScreenSettingVerification, UI_S(5), LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SpinnerScreenSettingVerification, lv_color_hex(0xB8B8B8),
                               LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SpinnerScreenSettingVerification, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SpinnerScreenSettingVerification, UI_S(5), LV_PART_INDICATOR | LV_STATE_DEFAULT);
}
