// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: UI_Setting

#include "../ui.h"
#include "ui_scale.h"

void ui_ScreenSettingMain_screen_init(void)
{
ui_ScreenSettingMain = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_ScreenSettingMain, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenSettingMain, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSettingMainContainer = lv_obj_create(ui_ScreenSettingMain);
lv_obj_set_width( ui_PanelSettingMainContainer, UI_SX(720));
lv_obj_set_height( ui_PanelSettingMainContainer, UI_SY(498));
lv_obj_set_x( ui_PanelSettingMainContainer, UI_SX(150) );
lv_obj_set_y( ui_PanelSettingMainContainer, UI_SY(58) );
lv_obj_set_flex_flow(ui_PanelSettingMainContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelSettingMainContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_pad_left(ui_PanelSettingMainContainer, UI_S(0), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelSettingMainContainer, UI_S(0), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelSettingMainContainer, UI_S(0), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelSettingMainContainer, UI_S(0), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSettingMainContainerItem1 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_height( ui_PanelSettingMainContainerItem1, UI_SY(70));
lv_obj_set_width( ui_PanelSettingMainContainerItem1, lv_pct(100));
lv_obj_set_y( ui_PanelSettingMainContainerItem1, UI_SY(-230) );
lv_obj_set_x( ui_PanelSettingMainContainerItem1, lv_pct(1) );
lv_obj_set_align( ui_PanelSettingMainContainerItem1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem1, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem1, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer1WiFi = lv_img_create(ui_PanelSettingMainContainerItem1);
lv_img_set_src(ui_ImagePanelSettingMainContainer1WiFi, &ui_img_wifi_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer1WiFi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer1WiFi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer1WiFi, UI_SY(2) );
lv_obj_set_x( ui_ImagePanelSettingMainContainer1WiFi, lv_pct(-48) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer1WiFi, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer1WiFi, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer1WiFi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelSettingMainContainer1Arrow = lv_img_create(ui_PanelSettingMainContainerItem1);
lv_img_set_src(ui_ImagePanelSettingMainContainer1Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer1Arrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer1Arrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer1Arrow, UI_SY(0) );
lv_obj_set_x( ui_ImagePanelSettingMainContainer1Arrow, lv_pct(49) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer1Arrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer1Arrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer1Arrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelSettingMainContainer1WiFi = lv_label_create(ui_PanelSettingMainContainerItem1);
lv_obj_set_width( ui_LabelPanelSettingMainContainer1WiFi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelSettingMainContainer1WiFi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelSettingMainContainer1WiFi, UI_SX(-240) );
lv_obj_set_y( ui_LabelPanelSettingMainContainer1WiFi, UI_SY(2) );
lv_obj_set_align( ui_LabelPanelSettingMainContainer1WiFi, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelSettingMainContainer1WiFi,"Wi-Fi");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer1WiFi, ui_font_scaled(30), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSettingMainContainerItem2 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_width( ui_PanelSettingMainContainerItem2, UI_SX(719));
lv_obj_set_height( ui_PanelSettingMainContainerItem2, UI_SY(70));
lv_obj_set_x( ui_PanelSettingMainContainerItem2, UI_SX(7) );
lv_obj_set_y( ui_PanelSettingMainContainerItem2, UI_SY(-130) );
lv_obj_set_align( ui_PanelSettingMainContainerItem2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem2, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem2, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer2Blue = lv_img_create(ui_PanelSettingMainContainerItem2);
lv_img_set_src(ui_ImagePanelSettingMainContainer2Blue, &ui_img_bluetooth_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer2Blue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer2Blue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer2Blue, UI_SY(2) );
lv_obj_set_x( ui_ImagePanelSettingMainContainer2Blue, lv_pct(-48) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer2Blue, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer2Blue, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer2Blue, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelSettingMainContainer2Arrow = lv_img_create(ui_PanelSettingMainContainerItem2);
lv_img_set_src(ui_ImagePanelSettingMainContainer2Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer2Arrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer2Arrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer2Arrow, UI_SY(0) );
lv_obj_set_x( ui_ImagePanelSettingMainContainer2Arrow, lv_pct(49) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer2Arrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer2Arrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer2Arrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelSettingMainContainer2Blue = lv_label_create(ui_PanelSettingMainContainerItem2);
lv_obj_set_width( ui_LabelPanelSettingMainContainer2Blue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelSettingMainContainer2Blue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelSettingMainContainer2Blue, UI_SX(-206) );
lv_obj_set_y( ui_LabelPanelSettingMainContainer2Blue, UI_SY(2) );
lv_obj_set_align( ui_LabelPanelSettingMainContainer2Blue, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelSettingMainContainer2Blue,"Bluetooth");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer2Blue, ui_font_scaled(30), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSettingMainContainerItem3 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_width( ui_PanelSettingMainContainerItem3, UI_SX(719));
lv_obj_set_height( ui_PanelSettingMainContainerItem3, UI_SY(70));
lv_obj_set_x( ui_PanelSettingMainContainerItem3, UI_SX(9) );
lv_obj_set_y( ui_PanelSettingMainContainerItem3, UI_SY(-30) );
lv_obj_set_align( ui_PanelSettingMainContainerItem3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem3, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem3, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer3Volume = lv_img_create(ui_PanelSettingMainContainerItem3);
lv_img_set_src(ui_ImagePanelSettingMainContainer3Volume, &ui_img_sound_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer3Volume, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer3Volume, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer3Volume, UI_SY(2) );
lv_obj_set_x( ui_ImagePanelSettingMainContainer3Volume, lv_pct(-48) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer3Volume, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer3Volume, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer3Volume, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelSettingMainContainer3Arrow = lv_img_create(ui_PanelSettingMainContainerItem3);
lv_img_set_src(ui_ImagePanelSettingMainContainer3Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer3Arrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer3Arrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer3Arrow, UI_SY(0) );
lv_obj_set_x( ui_ImagePanelSettingMainContainer3Arrow, lv_pct(49) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer3Arrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer3Arrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer3Arrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelSettingMainContainer3Volume = lv_label_create(ui_PanelSettingMainContainerItem3);
lv_obj_set_width( ui_LabelPanelSettingMainContainer3Volume, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelSettingMainContainer3Volume, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelSettingMainContainer3Volume, UI_SX(-221) );
lv_obj_set_y( ui_LabelPanelSettingMainContainer3Volume, UI_SY(1) );
lv_obj_set_align( ui_LabelPanelSettingMainContainer3Volume, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelSettingMainContainer3Volume,"Volume");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer3Volume, ui_font_scaled(30), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSettingMainContainerItem4 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_width( ui_PanelSettingMainContainerItem4, UI_SX(719));
lv_obj_set_height( ui_PanelSettingMainContainerItem4, UI_SY(70));
lv_obj_set_x( ui_PanelSettingMainContainerItem4, UI_SX(5) );
lv_obj_set_y( ui_PanelSettingMainContainerItem4, UI_SY(70) );
lv_obj_set_align( ui_PanelSettingMainContainerItem4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem4, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem4, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer4Light = lv_img_create(ui_PanelSettingMainContainerItem4);
lv_img_set_src(ui_ImagePanelSettingMainContainer4Light, &ui_img_light_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer4Light, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer4Light, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer4Light, UI_SY(2) );
lv_obj_set_x( ui_ImagePanelSettingMainContainer4Light, lv_pct(-48) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer4Light, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer4Light, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer4Light, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelSettingMainContainer4Arrow = lv_img_create(ui_PanelSettingMainContainerItem4);
lv_img_set_src(ui_ImagePanelSettingMainContainer4Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer4Arrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer4Arrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer4Arrow, UI_SY(0) );
lv_obj_set_x( ui_ImagePanelSettingMainContainer4Arrow, lv_pct(49) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer4Arrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer4Arrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer4Arrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelSettingMainContainer4Light = lv_label_create(ui_PanelSettingMainContainerItem4);
lv_obj_set_width( ui_LabelPanelSettingMainContainer4Light, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelSettingMainContainer4Light, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelSettingMainContainer4Light, UI_SX(-201) );
lv_obj_set_y( ui_LabelPanelSettingMainContainer4Light, UI_SY(2) );
lv_obj_set_align( ui_LabelPanelSettingMainContainer4Light, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelSettingMainContainer4Light,"Brightness");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer4Light, ui_font_scaled(30), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSettingMainContainerItem5 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_width( ui_PanelSettingMainContainerItem5, UI_SX(719));
lv_obj_set_height( ui_PanelSettingMainContainerItem5, UI_SY(70));
lv_obj_set_x( ui_PanelSettingMainContainerItem5, UI_SX(3) );
lv_obj_set_y( ui_PanelSettingMainContainerItem5, UI_SY(170) );
lv_obj_set_align( ui_PanelSettingMainContainerItem5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem5, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem5, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem5, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem5, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer5About = lv_img_create(ui_PanelSettingMainContainerItem5);
lv_img_set_src(ui_ImagePanelSettingMainContainer5About, &ui_img_about_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer5About, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer5About, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer5About, UI_SY(2) );
lv_obj_set_x( ui_ImagePanelSettingMainContainer5About, lv_pct(-48) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer5About, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer5About, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer5About, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImagePanelSettingMainContainer5Arrow = lv_img_create(ui_PanelSettingMainContainerItem5);
lv_img_set_src(ui_ImagePanelSettingMainContainer5Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer5Arrow, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePanelSettingMainContainer5Arrow, LV_SIZE_CONTENT);   /// 1
lv_obj_set_y( ui_ImagePanelSettingMainContainer5Arrow, UI_SY(0) );
lv_obj_set_x( ui_ImagePanelSettingMainContainer5Arrow, lv_pct(49) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer5Arrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer5Arrow, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer5Arrow, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelPanelSettingMainContainer5About = lv_label_create(ui_PanelSettingMainContainerItem5);
lv_obj_set_width( ui_LabelPanelSettingMainContainer5About, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelSettingMainContainer5About, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelSettingMainContainer5About, UI_SX(-183) );
lv_obj_set_y( ui_LabelPanelSettingMainContainer5About, UI_SY(1) );
lv_obj_set_align( ui_LabelPanelSettingMainContainer5About, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelSettingMainContainer5About,"About Device");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer5About, ui_font_scaled(30), LV_PART_MAIN| LV_STATE_DEFAULT);

// Item 6: ESP-NOW Audio
ui_PanelSettingMainContainerItem6 = lv_obj_create(ui_PanelSettingMainContainer);
lv_obj_set_width( ui_PanelSettingMainContainerItem6, UI_SX(719));
lv_obj_set_height( ui_PanelSettingMainContainerItem6, UI_SY(70));
lv_obj_set_x( ui_PanelSettingMainContainerItem6, UI_SX(3) );
lv_obj_set_y( ui_PanelSettingMainContainerItem6, UI_SY(270) );
lv_obj_set_align( ui_PanelSettingMainContainerItem6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSettingMainContainerItem6, LV_OBJ_FLAG_SCROLLABLE );
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelSettingMainContainerItem6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelSettingMainContainerItem6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem6, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem6, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_PanelSettingMainContainerItem6, lv_color_hex(0xCBCBCB), LV_PART_MAIN | LV_STATE_PRESSED );
lv_obj_set_style_bg_opa(ui_PanelSettingMainContainerItem6, 255, LV_PART_MAIN| LV_STATE_PRESSED);

ui_ImagePanelSettingMainContainer6ESPNOW = lv_img_create(ui_PanelSettingMainContainerItem6);
lv_img_set_src(ui_ImagePanelSettingMainContainer6ESPNOW, &ui_img_sound_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer6ESPNOW, LV_SIZE_CONTENT);
lv_obj_set_height( ui_ImagePanelSettingMainContainer6ESPNOW, LV_SIZE_CONTENT);
lv_obj_set_y( ui_ImagePanelSettingMainContainer6ESPNOW, UI_SY(2) );
lv_obj_set_x( ui_ImagePanelSettingMainContainer6ESPNOW, lv_pct(-48) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer6ESPNOW, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer6ESPNOW, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer6ESPNOW, LV_OBJ_FLAG_SCROLLABLE );

ui_ImagePanelSettingMainContainer6Arrow = lv_img_create(ui_PanelSettingMainContainerItem6);
lv_img_set_src(ui_ImagePanelSettingMainContainer6Arrow, &ui_img_arrow_png);
lv_obj_set_width( ui_ImagePanelSettingMainContainer6Arrow, LV_SIZE_CONTENT);
lv_obj_set_height( ui_ImagePanelSettingMainContainer6Arrow, LV_SIZE_CONTENT);
lv_obj_set_y( ui_ImagePanelSettingMainContainer6Arrow, UI_SY(0) );
lv_obj_set_x( ui_ImagePanelSettingMainContainer6Arrow, lv_pct(49) );
lv_obj_set_align( ui_ImagePanelSettingMainContainer6Arrow, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImagePanelSettingMainContainer6Arrow, LV_OBJ_FLAG_ADV_HITTEST );
lv_obj_clear_flag( ui_ImagePanelSettingMainContainer6Arrow, LV_OBJ_FLAG_SCROLLABLE );

ui_LabelPanelSettingMainContainer6ESPNOW = lv_label_create(ui_PanelSettingMainContainerItem6);
lv_obj_set_width( ui_LabelPanelSettingMainContainer6ESPNOW, LV_SIZE_CONTENT);
lv_obj_set_height( ui_LabelPanelSettingMainContainer6ESPNOW, LV_SIZE_CONTENT);
lv_obj_set_x( ui_LabelPanelSettingMainContainer6ESPNOW, UI_SX(-145) );
lv_obj_set_y( ui_LabelPanelSettingMainContainer6ESPNOW, UI_SY(1) );
lv_obj_set_align( ui_LabelPanelSettingMainContainer6ESPNOW, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelSettingMainContainer6ESPNOW,"Assistive Listening");
lv_obj_set_style_text_font(ui_LabelPanelSettingMainContainer6ESPNOW, ui_font_scaled(30), LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_PanelSettingMainContainerItem1, ui_event_PanelSettingMainContainerItem1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelSettingMainContainerItem2, ui_event_PanelSettingMainContainerItem2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelSettingMainContainerItem3, ui_event_PanelSettingMainContainerItem3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelSettingMainContainerItem4, ui_event_PanelSettingMainContainerItem4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelSettingMainContainerItem5, ui_event_PanelSettingMainContainerItem5, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PanelSettingMainContainerItem6, ui_event_PanelSettingMainContainerItem6, LV_EVENT_ALL, NULL);

}
