// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.3
// LVGL version: 8.3.6
// Project name: UI_Setting

#include "../ui.h"
#include "ui_scale.h"

void ui_ScreenSettingAbout_screen_init(void)
{
ui_ScreenSettingAbout = lv_obj_create(NULL);
lv_obj_set_style_bg_color(ui_ScreenSettingAbout, lv_color_hex(0xE5F3FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenSettingAbout, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelScreenSettingAboutList = lv_obj_create(ui_ScreenSettingAbout);
lv_obj_set_width( ui_PanelScreenSettingAboutList, lv_pct(88));
lv_obj_set_height( ui_PanelScreenSettingAboutList, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PanelScreenSettingAboutList, UI_SX(43) );
lv_obj_set_y( ui_PanelScreenSettingAboutList, UI_SY(77) );
lv_obj_set_flex_flow(ui_PanelScreenSettingAboutList,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelScreenSettingAboutList, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_add_flag( ui_PanelScreenSettingAboutList, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_radius(ui_PanelScreenSettingAboutList, UI_S(10), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpinnerScreenAboutList = lv_spinner_create(ui_ScreenSettingAbout,1000,90);
lv_obj_set_width( ui_SpinnerScreenAboutList, lv_pct(16));
lv_obj_set_height( ui_SpinnerScreenAboutList, lv_pct(16));
lv_obj_set_align( ui_SpinnerScreenAboutList, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SpinnerScreenAboutList, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_SpinnerScreenAboutList, LV_OBJ_FLAG_CLICKABLE );    /// Flags
lv_obj_set_style_arc_width(ui_SpinnerScreenAboutList, UI_S(5), LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_SpinnerScreenAboutList, lv_color_hex(0xC2C2C2), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_SpinnerScreenAboutList, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_SpinnerScreenAboutList, UI_S(5), LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_ButtonScreenSettingAboutReturn = lv_btn_create(ui_ScreenSettingAbout);
lv_obj_set_width( ui_ButtonScreenSettingAboutReturn, UI_SX(60));
lv_obj_set_height( ui_ButtonScreenSettingAboutReturn, UI_SY(60));
lv_obj_set_x(ui_ButtonScreenSettingAboutReturn, UI_SX(-460) );
lv_obj_set_y(ui_ButtonScreenSettingAboutReturn, UI_SY(-240) );
lv_obj_set_align( ui_ButtonScreenSettingAboutReturn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonScreenSettingAboutReturn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonScreenSettingAboutReturn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ButtonScreenSettingAboutReturn, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonScreenSettingAboutReturn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageScreenSettingAboutReturn = lv_img_create(ui_ButtonScreenSettingAboutReturn);
lv_img_set_src(ui_ImageScreenSettingAboutReturn, &ui_img_return_png);
lv_obj_set_width( ui_ImageScreenSettingAboutReturn, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageScreenSettingAboutReturn, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ImageScreenSettingAboutReturn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageScreenSettingAboutReturn, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageScreenSettingAboutReturn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_img_recolor(ui_ImageScreenSettingAboutReturn, lv_color_hex(0x000000), LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_img_recolor_opa(ui_ImageScreenSettingAboutReturn, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

// ui_ImageScreenSettingAbout = lv_img_create(ui_ScreenSettingAbout);
// lv_img_set_src(ui_ImageScreenSettingAbout, &ui_img_482951309);
// lv_obj_set_width( ui_ImageScreenSettingAbout, LV_SIZE_CONTENT);  /// 1
// lv_obj_set_height( ui_ImageScreenSettingAbout, LV_SIZE_CONTENT);   /// 1
// lv_obj_set_x( ui_ImageScreenSettingAbout, UI_SX(-21) );
// lv_obj_set_y( ui_ImageScreenSettingAbout, UI_SY(-446) );
// lv_obj_set_align( ui_ImageScreenSettingAbout, LV_ALIGN_CENTER );
// lv_obj_add_flag( ui_ImageScreenSettingAbout, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
// lv_obj_clear_flag( ui_ImageScreenSettingAbout, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PanelScreenSettingAbout = lv_obj_create(ui_ScreenSettingAbout);
lv_obj_set_width( ui_PanelScreenSettingAbout, UI_SX(752));
lv_obj_set_height( ui_PanelScreenSettingAbout, UI_SY(588));
lv_obj_set_x( ui_PanelScreenSettingAbout, UI_SX(0) );
lv_obj_set_y( ui_PanelScreenSettingAbout, UI_SY(33) );
lv_obj_set_align( ui_PanelScreenSettingAbout, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelScreenSettingAbout,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelScreenSettingAbout, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_PanelScreenSettingAbout, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_PanelPanelScreenSettingAbout = lv_obj_create(ui_PanelScreenSettingAbout);
lv_obj_set_width( ui_PanelPanelScreenSettingAbout, UI_SX(716));
lv_obj_set_height( ui_PanelPanelScreenSettingAbout, UI_SY(82));
lv_obj_set_x( ui_PanelPanelScreenSettingAbout, UI_SX(53) );
lv_obj_set_y( ui_PanelPanelScreenSettingAbout, UI_SY(915) );
lv_obj_set_align( ui_PanelPanelScreenSettingAbout, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPanelScreenSettingAbout, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelPanelScreenSettingAbout, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPanelScreenSettingAbout, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAboutDevice = lv_label_create(ui_PanelPanelScreenSettingAbout);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAboutDevice, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAboutDevice, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAboutDevice, UI_SX(-252) );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAboutDevice, UI_SY(1) );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAboutDevice, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAboutDevice,"Device Name");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAboutDevice, ui_font_scaled(24), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAbout2 = lv_label_create(ui_PanelPanelScreenSettingAbout);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAbout2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAbout2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAbout2, UI_SX(227) );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAbout2, UI_SY(-1) );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAbout2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAbout2,"ESP32-P4");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAbout2, ui_font_scaled(24), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPanelScreenSettingAbout1 = lv_obj_create(ui_PanelScreenSettingAbout);
lv_obj_set_width( ui_PanelPanelScreenSettingAbout1, UI_SX(716));
lv_obj_set_height( ui_PanelPanelScreenSettingAbout1, UI_SY(82));
lv_obj_set_x( ui_PanelPanelScreenSettingAbout1, UI_SX(1) );
lv_obj_set_y( ui_PanelPanelScreenSettingAbout1, UI_SY(-15) );
lv_obj_set_align( ui_PanelPanelScreenSettingAbout1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPanelScreenSettingAbout1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelPanelScreenSettingAbout1, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPanelScreenSettingAbout1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAboutManufacturer = lv_label_create(ui_PanelPanelScreenSettingAbout1);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAboutManufacturer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAboutManufacturer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAboutManufacturer, UI_SX(-252) );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAboutManufacturer, UI_SY(1) );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAboutManufacturer, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAboutManufacturer,"Manufacturer");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAboutManufacturer, ui_font_scaled(24), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAbout1 = lv_label_create(ui_PanelPanelScreenSettingAbout1);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAbout1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAbout1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAbout1, UI_SX(233) );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAbout1, UI_SY(-2) );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAbout1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAbout1,"ELECROW");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAbout1, ui_font_scaled(24), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPanelScreenSettingAbout2 = lv_obj_create(ui_PanelScreenSettingAbout);
lv_obj_set_width( ui_PanelPanelScreenSettingAbout2, UI_SX(716));
lv_obj_set_height( ui_PanelPanelScreenSettingAbout2, UI_SY(82));
lv_obj_set_x( ui_PanelPanelScreenSettingAbout2, UI_SX(1) );
lv_obj_set_y( ui_PanelPanelScreenSettingAbout2, UI_SY(-15) );
lv_obj_set_align( ui_PanelPanelScreenSettingAbout2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPanelScreenSettingAbout2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelPanelScreenSettingAbout2, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPanelScreenSettingAbout2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAboutMAC = lv_label_create(ui_PanelPanelScreenSettingAbout2);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAboutMAC, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAboutMAC, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAboutMAC, UI_SX(-306) );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAboutMAC, UI_SY(1) );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAboutMAC, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAboutMAC,"MAC");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAboutMAC, ui_font_scaled(24), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAbout3 = lv_label_create(ui_PanelPanelScreenSettingAbout2);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAbout3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAbout3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAbout3, UI_SX(233) );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAbout3, UI_SY(-2) );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAbout3, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAbout3,"---------------");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAbout3, ui_font_scaled(24), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPanelScreenSettingAbout3 = lv_obj_create(ui_PanelScreenSettingAbout);
lv_obj_set_width( ui_PanelPanelScreenSettingAbout3, UI_SX(716));
lv_obj_set_height( ui_PanelPanelScreenSettingAbout3, UI_SY(82));
lv_obj_set_x( ui_PanelPanelScreenSettingAbout3, UI_SX(1) );
lv_obj_set_y( ui_PanelPanelScreenSettingAbout3, UI_SY(-15) );
lv_obj_set_align( ui_PanelPanelScreenSettingAbout3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPanelScreenSettingAbout3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelPanelScreenSettingAbout3, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPanelScreenSettingAbout3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAboutUIFramework = lv_label_create(ui_PanelPanelScreenSettingAbout3);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAboutUIFramework, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAboutUIFramework, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAboutUIFramework, UI_SX(-250) );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAboutUIFramework, UI_SY(2) );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAboutUIFramework, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAboutUIFramework,"UI Framework");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAboutUIFramework, ui_font_scaled(24), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAbout4 = lv_label_create(ui_PanelPanelScreenSettingAbout3);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAbout4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAbout4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAbout4, UI_SX(227) );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAbout4, UI_SY(0) );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAbout4, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAbout4,"ESP32_UI");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAbout4, ui_font_scaled(24), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPanelScreenSettingAbout4 = lv_obj_create(ui_PanelScreenSettingAbout);
lv_obj_set_width( ui_PanelPanelScreenSettingAbout4, UI_SX(716));
lv_obj_set_height( ui_PanelPanelScreenSettingAbout4, UI_SY(82));
lv_obj_set_x( ui_PanelPanelScreenSettingAbout4, UI_SX(1) );
lv_obj_set_y( ui_PanelPanelScreenSettingAbout4, UI_SY(-15) );
lv_obj_set_align( ui_PanelPanelScreenSettingAbout4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPanelScreenSettingAbout4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelPanelScreenSettingAbout4, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPanelScreenSettingAbout4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAboutSoftwareVersion = lv_label_create(ui_PanelPanelScreenSettingAbout4);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAboutSoftwareVersion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAboutSoftwareVersion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAboutSoftwareVersion, UI_SX(-236) );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAboutSoftwareVersion, UI_SY(2) );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAboutSoftwareVersion, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAboutSoftwareVersion,"Firmware Version");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAboutSoftwareVersion, ui_font_scaled(24), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAbout5 = lv_label_create(ui_PanelPanelScreenSettingAbout4);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAbout5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAbout5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAbout5, UI_SX(235) );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAbout5, UI_SY(-2) );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAbout5, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAbout5,"---------------");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAbout5, ui_font_scaled(24), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPanelScreenSettingAbout5 = lv_obj_create(ui_PanelScreenSettingAbout);
lv_obj_set_width( ui_PanelPanelScreenSettingAbout5, UI_SX(716));
lv_obj_set_height( ui_PanelPanelScreenSettingAbout5, UI_SY(82));
lv_obj_set_x( ui_PanelPanelScreenSettingAbout5, UI_SX(1) );
lv_obj_set_y( ui_PanelPanelScreenSettingAbout5, UI_SY(-15) );
lv_obj_set_align( ui_PanelPanelScreenSettingAbout5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPanelScreenSettingAbout5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_PanelPanelScreenSettingAbout5, lv_color_hex(0xF6F6F6), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPanelScreenSettingAbout5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion = lv_label_create(ui_PanelPanelScreenSettingAbout5);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion, UI_SX(-205) );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion, UI_SY(2) );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion,"UI Framework Version");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAboutUIFrameworkVersion, ui_font_scaled(24), LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPanelPanelScreenSettingAbout6 = lv_label_create(ui_PanelPanelScreenSettingAbout5);
lv_obj_set_width( ui_LabelPanelPanelScreenSettingAbout6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPanelPanelScreenSettingAbout6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPanelPanelScreenSettingAbout6, UI_SX(235) );
lv_obj_set_y( ui_LabelPanelPanelScreenSettingAbout6, UI_SY(-2) );
lv_obj_set_align( ui_LabelPanelPanelScreenSettingAbout6, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPanelPanelScreenSettingAbout6,"---------------");
lv_obj_set_style_text_font(ui_LabelPanelPanelScreenSettingAbout6, ui_font_scaled(24), LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ButtonScreenSettingAboutReturn, ui_event_ButtonScreenSettingAboutReturn, LV_EVENT_ALL, NULL);

}
